[package]
name = "programming-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "actix-web"
path = "src/bin/ch1/actix-web.rs"
